lint:
  files_exist:
    - assets/multiqc_config.yml
    - assets/nf-core-sequencecomposition_logo_light.png
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - docs/images/nf-core-sequencecomposition_logo_light.png
    - docs/images/nf-core-sequencecomposition_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - LICENSE
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - assets/sendmail_template.txt
    - .gitattributes
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - config_defaults:
        - params.selected_fw_output
nf_core_version: 3.5.2
repository_type: pipeline
template:
  author: "@muffato"
  description: Pipeline that extracts statistics from a genome about its sequence
    composition
  force: false
  is_nfcore: false
  name: sequencecomposition
  org: sanger-tol
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 1.3.0dev
