contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #sanger-tol-sequencecomposition channel"
    url: https://nfcore.slack.com/channels/sanger-tol-sequencecomposition
    about: Discussion about the sanger-tol/sequencecomposition pipeline
